
!not sure what this does...
MODULE FTN_C_1
  USE, INTRINSIC :: ISO_C_BINDING
END MODULE FTN_C_1

! The module for mapping to the C++ (via C) code
MODULE CELLML_MODEL_DEFINITION
  INTERFACE
     TYPE (C_PTR) FUNCTION CREATE_CELLML_MODEL_DEFINITION (URI) &
          BIND(C, NAME='create_cellml_model_definition_f')
       CHARACTER*(*) URI
     END FUNCTION CREATE_CELLML_MODEL_DEFINITION
  END INTERFACE
END MODULE CELLML_MODEL_DEFINITION
