PROGRAM testF2C
  USE, INTRINSIC :: ISO_C_BINDING
  INTERFACE
     INTEGER (C_INT) FUNCTION C_LIBRARY_FUNCTION &
          (EXP1,ALLOC,LEN_ALLOC) BIND(C)
       USE ISO_C_BINDING
       INTEGER (C_INT) :: EXP1(100)
       REAL (C_FLOAT) :: ALLOC(*)
       INTEGER (C_INT), VALUE :: LEN_ALLOC
     END FUNCTION C_LIBRARY_FUNCTION
  END INTERFACE
  INTEGER (C_INT) :: EXP1(100)
  REAL (C_FLOAT), ALLOCATABLE :: ALLOC(:)
  INTEGER (C_INT) :: LEN_ALLOC,X1
  WRITE(*,*) 'F Testing Fortran calling C'
  WRITE(*,*) 'F - C_INT   = ',C_INT
  WRITE(*,*) 'F - C_FLOAT = ',C_FLOAT

  LEN_ALLOC = 200
  ALLOCATE(ALLOC(LEN_ALLOC))

  X1 = C_LIBRARY_FUNCTION(EXP1,ALLOC,LEN_ALLOC)

  WRITE(*,*) 'F => X1 = ',X1

END PROGRAM testF2C
