PROGRAM testF2C
  USE, INTRINSIC :: ISO_C_BINDING
  INTERFACE
     INTEGER (C_INT) FUNCTION C_LIBRARY_FUNCTION &
          (EXP1,ALLOC,LEN_ALLOC) BIND(C)
       USE ISO_C_BINDING
       INTEGER (C_INT) :: EXP1(100)
       REAL (C_FLOAT) :: ALLOC(*)
       INTEGER (C_INT), VALUE :: LEN_ALLOC
     END FUNCTION C_LIBRARY_FUNCTION
     FUNCTION CREATE_BOB() BIND(C,NAME='createBob')
       USE ISO_C_BINDING
       TYPE (C_PTR) :: CREATE_BOB
     END FUNCTION CREATE_BOB
     SUBROUTINE BOB_PRINT_NAME(BOB) BIND(C,NAME='bobPrintName')
       USE ISO_C_BINDING
       TYPE (C_PTR), VALUE :: BOB
     END SUBROUTINE BOB_PRINT_NAME
  END INTERFACE
  INTEGER (C_INT) :: EXP1(100)
  REAL (C_FLOAT), ALLOCATABLE :: ALLOC(:)
  INTEGER (C_INT) :: LEN_ALLOC,X1
  TYPE (C_PTR) :: X2
  WRITE(*,*) 'F Testing Fortran calling C'
  WRITE(*,*) 'F - C_INT   = ',C_INT
  WRITE(*,*) 'F - C_FLOAT = ',C_FLOAT

  LEN_ALLOC = 200
  ALLOCATE(ALLOC(LEN_ALLOC))

  X1 = C_LIBRARY_FUNCTION(EXP1,ALLOC,LEN_ALLOC)

  WRITE(*,*) 'F X1 = ',X1
  WRITE(*,*) 'F ALLOC(1) = ',ALLOC(1)
  WRITE(*,*) 'F ALLOC(4) = ',ALLOC(4)
  WRITE(*,*) 'F ALLOC(LEN_ALLOC) = ',ALLOC(LEN_ALLOC)

  X2 = CREATE_BOB()
  IF (.NOT. C_ASSOCIATED(X2)) THEN
     WRITE(*,*) 'F Error creating a Bob object'
     STOP
  END IF
  WRITE(*,*) 'F Created Bob'
  CALL BOB_PRINT_NAME(X2)
END PROGRAM testF2C
